version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
  versioning-strategy: "increase"
  open-pull-requests-limit: 3
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: monthly
