<?php

namespace Boomerang\ExpectationResults;

use Boomerang\Interfaces\ExpectationResultInterface;

class MutedExpectationResult extends AbstractResult {

	/**
	 * @var \Boomerang\Interfaces\ExpectationResultInterface
	 */
	private $expecationResult;

	/**
	 * @param ExpectationResultInterface $expectationResult
	 */
	public function __construct( ExpectationResultInterface $expectationResult ) {
		$this->expecationResult = $expectationResult;
		parent::__construct($expectationResult->getValidator(), $expectationResult->getMessage()); // TODO: Change the autogenerated stub
	}

	/**
	 * @return \Boomerang\Interfaces\ExpectationResultInterface
	 */
	public function getExpecationResult() {
		return $this->expecationResult;
	}

}